CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT false,
  force_password_reset BOOLEAN DEFAULT false,
  last_signin_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE visibility (
  class VARCHAR(10) UNIQUE NOT NULL
) DEFAULT CHARSET=utf8mb4;

INSERT INTO visibility VALUES ('public');
INSERT INTO visibility VALUES ('private');

CREATE TABLE license (
  type VARCHAR(30) UNIQUE NOT NULL
) DEFAULT CHARSET=utf8mb4;

INSERT INTO license VALUES ('No License');
INSERT INTO license VALUES ('CC0');
#TODO: add other licenses.

CREATE TABLE albums (
  name VARCHAR(255) NOT NULL PRIMARY KEY,
  description VARCHAR(255) NOT NULL DEFAULT '',
  visibility VARCHAR(10) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(visibility) REFERENCES visibility(class)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE images (
  name VARCHAR(255) NOT NULL PRIMARY KEY,
  original_name VARCHAR(255) DEFAULT '',
  thumbnail VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT '',
  album VARCHAR(255) NOT NULL DEFAULT '',
  visibility VARCHAR(10) NOT NULL,
  license VARCHAR(30) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(album) REFERENCES albums(name),
  FOREIGN KEY(visibility) REFERENCES visibility(class),
  FOREIGN KEY(license) REFERENCES license(type)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE tags (
  name VARCHAR(30) UNIQUE NOT NULL
) DEFAULT CHARSET=utf8mb4;
